import "@storybook/addon-a11y/register";
import "@storybook/addon-docs/register";
import "@storybook/addon-actions/register";
import "@storybook/addon-centered/react";
import "@storybook/addon-knobs/register";
import "@storybook/addon-viewport/register";
import "@storybook/addon-notes/register";
import "@storybook/addon-essentials";
import "@storybook/addon-backgrounds";
// import '@storybook/preset-create-react-app';
