name: Build CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Test application and make sure it runs on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]

    steps:
    - name: Checkout to current branch
      uses: actions/checkout@v2

    - name: Configure Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        echo 'Running Setup...'
        yarn install

    - name: Build HackMerced Hub
      run: |
        echo 'Building HackMerced Hub...'
        yarn build
